### ISSUE TITLE
Google Plus icon

### ISSUE THREAD

**Issue by medinarodel** [lwe/entypo-rails#14]
Hi Sir!

I am trying to use google plus icon. I checked your generated CSS and it has this line

```CSS
/* f30e */

.icon-social-google + :before {
  content: '\f30f';
}

/* f30f */
.icon-social-c-google + :before {
  content: '\f310';
}
```

I think that won't work because it will be treated as invalid css (name). 
Can we use something like icon-social-google-plus & icon-social-c-google-plus?

By the way, as a workaround, I added this in my css file:

````CSS
.icon-social-google-plus:before {
  content: '\f30f';
}
````

thanks!
